Repository haifahrul/code-converter, pull requests merged in 2020-10, with the labels that each got.

#2 Create CONTRIBUTING.md
  CONTRIBUTING.md
Labels: Hacktoberfest

#3 Update README.md
  README.md
Labels: hacktoberfest

#5 w/signoff
  src/bytes_to_json.js
Labels: feature request, hacktoberfest

#6 Home page/sankalpa fernando
  assets/style.css
  package-lock.json
  package.json
  public/assets/Taieri.png
  public/assets/Waimakariri.png
  public/assets/index.js
  public/assets/style.css
  server.js
  src/index.js
  view/index.html
Labels: feature request, hacktoberfest

#7 w/signoff
  package-lock.json
  package.json
  server.js
  view/index.html
Labels: feature request, hacktoberfest
